version: '3'

services:
  server:
    container_name: server
    build:
      context: ./docker/nginx
    networks:
      - node-network
    ports:
      - "8080:80"
    depends_on:
      - app

  app:
    build:
      context: ./docker/node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 120s docker-entrypoint.sh
    #command: nodemon index.js
    command: sh -c "npm i && node index.js"
    networks:
      - node-network
    volumes:
      - .:/usr/src/app
    tty: true
    expose: 
      - 3000
    depends_on: 
      - db


  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network

networks:
  node-network:
    driver: bridge
